server:
  port: 8000

spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test_java_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true