server:
  port: 8000

app:
  enabled-sort-fields:
    - price
    - color

spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5432/test_java_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true