server:
  port: 8000

app:
  enabled-sort-fields:
    - price
    - color

loan:
  minimalIncome: 40000
  minimalCarPrice: 1000000
  maxAnnualIncomeLoanAmount: 0.5
  maxCarPriceLoanAmount: 0.3
  income-api: https://66055cd12ca9478ea1801f2e.mockapi.io/api/users/income


spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5432/test_java_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

income-client:
  enable: true
  api: https://66055cd12ca9478ea1801f2e.mockapi.io/api/users/income